import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono, Syne_Mono } from "next/font/google";

import "./globals.css";

const syneMono = Syne_Mono({
  variable: "--font-syne-mono",
  subsets: ["latin"],
  weight: "400",
});

const janeAusten = localFont({
  src: "../assets/fonts/jane_austen/JaneAust.ttf",
  variable: "--font-jane-austen",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${syneMono.variable} ${janeAusten.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
